# Generated by Django 5.1.1 on 2024-09-24 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('start_point_x', models.FloatField()),
                ('start_point_y', models.FloatField()),
                ('end_point_x', models.FloatField()),
                ('end_point_y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('width', models.FloatField()),
                ('length', models.FloatField()),
                ('floor', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_number', models.CharField(max_length=10)),
                ('equipment_number', models.CharField(blank=True, max_length=10, unique=True)),
                ('position_x', models.FloatField()),
                ('position_y', models.FloatField()),
                ('size_width', models.FloatField()),
                ('size_length', models.FloatField()),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantlayout.line')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('start_point_x', models.FloatField()),
                ('start_point_y', models.FloatField()),
                ('end_point_x', models.FloatField()),
                ('end_point_y', models.FloatField()),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantlayout.plant')),
            ],
        ),
        migrations.AddField(
            model_name='line',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantlayout.unit'),
        ),
    ]
