# Generated by Django 5.1.1 on 2024-09-23 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pemledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PECS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('equipment_number', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('date_written', models.DateField(auto_now_add=True)),
                ('rating', models.CharField(max_length=2)),
                ('insp_interval', models.CharField(choices=[('D', '일일'), ('W', '주간'), ('M', '월간'), ('Q', '분기'), ('H', '반기'), ('Y', '연간')], max_length=1)),
                ('order', models.IntegerField()),
                ('insp_point', models.CharField(max_length=50)),
                ('insp_item', models.CharField(max_length=100)),
                ('insp_int_rating', models.CharField(max_length=10)),
                ('insp_method', models.CharField(max_length=100)),
                ('judge_criteria', models.CharField(max_length=100)),
                ('actions_required', models.CharField(max_length=100)),
                ('management_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pemledger.managementteam')),
            ],
        ),
    ]
