# Generated by Django 5.1.1 on 2024-09-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecstandard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pecs',
            name='management_team',
            field=models.CharField(max_length=50),
        ),
    ]
