# Generated by Django 5.1.1 on 2024-09-28 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pemledger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='line_name',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='plant_location',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='plant_name',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='process_name',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='process_number',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='supplier_name',
        ),
    ]
