# Generated by Django 5.1.1 on 2024-09-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecstandard', '0002_alter_pecs_management_team'),
        ('pemledger', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManagementTeam',
        ),
        migrations.AddField(
            model_name='equipment',
            name='floor',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='line_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='plant_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='plant_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='process_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='process_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
