# Generated by Django 5.1.1 on 2024-09-29 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pemledger', '0003_equipment_floor_equipment_line_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='plant_location',
        ),
    ]
