# Generated by Django 5.1.1 on 2024-09-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemledger', '0004_remove_equipment_plant_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_number',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
