# Generated by Django 5.1.1 on 2024-09-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemledger', '0005_alter_equipment_equipment_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(blank=True, max_length=10, null=True)),
                ('plant_name', models.CharField(blank=True, max_length=2, null=True)),
                ('floor', models.CharField(blank=True, max_length=2, null=True)),
                ('line_name', models.CharField(blank=True, max_length=5, null=True)),
                ('left', models.IntegerField()),
                ('top', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('rotation', models.IntegerField(blank=True, null=True)),
                ('equipment_number', models.CharField(blank=True, max_length=5, null=True, unique=True)),
            ],
        ),
    ]
