# Generated by Django 5.1.1 on 2024-09-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_number', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('mfg_date', models.CharField(max_length=255)),
                ('mfg_number', models.CharField(max_length=255)),
                ('equipment_type', models.CharField(max_length=255)),
                ('specs', models.CharField(max_length=255)),
            ],
        ),
    ]
