# Generated by Django 5.1.1 on 2024-09-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_number', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=10)),
                ('model_name', models.CharField(max_length=15)),
                ('manufacturer', models.CharField(max_length=10)),
                ('mfg_date', models.DateField(blank=True, null=True)),
                ('mfg_number', models.CharField(blank=True, max_length=10, null=True)),
                ('equipment_type', models.CharField(blank=True, max_length=15, null=True)),
                ('specs', models.TextField(blank=True, null=True)),
                ('first_install', models.DateField()),
                ('first_implement', models.DateField(blank=True, null=True)),
                ('current_operation_place', models.CharField(max_length=10)),
                ('management_team', models.CharField(max_length=10)),
                ('overhaul', models.CharField(blank=True, max_length=10, null=True)),
                ('current_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ManagementTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
