# Generated by Django 5.1.1 on 2024-09-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='current_operation_place',
            field=models.CharField(default='unknown', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='current_status',
            field=models.CharField(default='unknown', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='first_implement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='first_install',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='management_team',
            field=models.CharField(default='unknown', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='overhaul',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_number',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='manufacturer',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='mfg_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='mfg_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='model_name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='specs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
