# Generated by Django 5.1.1 on 2024-09-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='current_operation_place',
            field=models.CharField(default='unknown', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='current_status',
            field=models.CharField(default='unknown', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='first_implement',
            field=models.CharField(default='unknown', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='first_install',
            field=models.CharField(default='unknown', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='management_team',
            field=models.CharField(default='unknown', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='overall',
            field=models.CharField(default='unknown', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='manufacturer',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='mfg_date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='mfg_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='model_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='specs',
            field=models.CharField(max_length=20),
        ),
    ]
