# Generated by Django 5.1.1 on 2024-09-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='specs',
            field=models.CharField(max_length=255),
        ),
    ]
