# Generated by Django 5.1.1 on 2024-09-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_equipment_current_operation_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='overhaul',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
