# Generated by Django 5.1.1 on 2024-09-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_equipment_specs'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='mfg_date',
            field=models.DateField(default='2024-09-01'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='mfg_number',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='model_name',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='types',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
