# Generated by Django 5.1.1 on 2024-09-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_equipment_mfg_date_equipment_mfg_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='mfg_date',
            field=models.CharField(max_length=255),
        ),
    ]
