# Generated by Django 5.1.1 on 2024-09-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfcstandard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pfcs',
            name='actions_required',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pfcs',
            name='date_written',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pfcs',
            name='insp_interval',
            field=models.CharField(choices=[('D', '일일'), ('W', '주간'), ('M', '월간'), ('Q', '분기'), ('H', '반기'), ('Y', '연간')], max_length=1),
        ),
        migrations.AlterField(
            model_name='pfcs',
            name='insp_item',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pfcs',
            name='insp_method',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pfcs',
            name='insp_point',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pfcs',
            name='judge_criteria',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pfcs',
            name='management_team',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pfcs',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pfcs',
            name='rating',
            field=models.CharField(max_length=2),
        ),
    ]
